<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View our Animals</title>
</head>
<h1>Animals</h1>


<body>

<form action = 'Animals.phtml' method = 'POST'>
<select name="animalMenu">
     <?php
     require_once '../PHP/Config.php';

     $sql = 'SELECT * from ANIMAL';
     $stmt = $PDO->prepare($sql);
     $stmt->execute();





     while ($row = $stmt->fetch()) {

         echo '<option value = "' . $row->name . '">' . $row->name . '</option>';
     }
     ?>
</select>
    <nav class="navbar navbar-default">
    </nav>
    <div class="col-md-3"></div>
    <div class="col-md-6 well">
        <h3 class="text-primary">Animals in ZooWeeMama</h3>
        <hr style="border-top:1px dotted #ccc;"/>
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form method="POST" action="">
                <button class="btn btn-primary" name="display">Display Animals</button>
            </form>
            <br /><br />
            <table class="table table-bordered">
                <thead class="alert-info">
                <tr>
                    <th>name</th>
                    <th>age</th>
                    <th>f_name</th>
                    <th>e_name</th>
                </tr>
                </thead>
                <tbody style="background-color:#fff;">
                <?php include'../PHP/Config.php'?>
                </tbody>
            </table>
        </div>
    </div>

    <?php
    require_once '../PHP/Config.php';

    if(ISSET($_POST['display'])){
        $sql = "SELECT * FROM ANIMAL";
        $query = $PDO->prepare($sql);
        $query->execute();

        while($fetch = $query->fetch()){
            ?>

            <tr>
                <td><?php echo $fetch->name?></td>
                <td><?php echo $fetch->age?></td>
                <td><?php echo $fetch->f_name?></td>
                <td><?php echo $fetch->e_name?></td>
            </tr>
            <?php
        }
    }
    ?>
</form>
</body>
</html>