<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <title>ZooWeeMama</title>
        <h>ZooWeeMama</h>
    </head>
    <body>

    <form>

        <input type = "text" name="Username" placeholder="UserName">
        <br>
        <input type="text" name = "Password" placeholder="Password">
        <br>
        <button class= "btn btn-success mt-3" name = "Login">Login</button>


    </form>


    </body>






<?php
$message = "kill yourself";
echo $message;

?>

</html>