<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View our Stores</title>
</head>
<h1>Stores</h1>

<body>

    <nav class="navbar navbar-default">
    </nav>
    <div class="col-md-3"></div>
    <div class="col-md-6 well">
        <h3 class="text-primary">Stores in ZooWeeMama</h3>
        <hr style="border-top:1px dotted #ccc;"/>
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form method="POST" action="">
                <button class="btn btn-primary" name="display">Display Stores</button>
            </form>
            <br /><br />
            <table class="table table-bordered">
                <thead class="alert-info">
                <tr>
                    <th>name</th>
                    <th>type</th>
                    <th>b_name</th>
                </tr>
                </thead>
                <tbody style="background-color:#fff;">
                <?php include'../PHP/Config.php'?>
                </tbody>
            </table>
        </div>
    </div>

    <?php
    require_once '../PHP/Config.php';

    if(ISSET($_POST['display'])){
        $sql = "SELECT * FROM STORE";
        $query = $PDO->prepare($sql);
        $query->execute();

        while($fetch = $query->fetch()){
            ?>

            <tr>
                <td><?php echo $fetch->name?></td>
                <td><?php echo $fetch->type?></td>
                <td><?php echo $fetch->b_name?></td>
            </tr>

            <?php
        }
    }
    ?>
</form>
</body>
</html>
