<?php
session_start() ?>

<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Manage Events</title>

</head>

<body>

<div>
    <h2>Here are all the events and options for events:</h2>
    <div>
        <?php

        require_once '../../PHP/config.php';
        ?>
        <div>Add a Event</div>
        <div>
            <form action="Manger_Events.phtml" method="post">
                <label for="Name">Name:
                    <input type="text" , name="Name"
                </label>
                <br>
                <label for="Time"> Time:
                    <input type="date" , name="Time">
                </label>
                <br>
                <label for="Time">Cost:
                    <input type="number" , name="Time">
                </label>
                <br>
                <label for="Capacity">Capacity:
                    <input type="number" , name="Capacity">
                </label>
                <br>
                <label for="Building:">Building:
                    <select name="Building"
                            id="Building">
                        <?php
                        $Query = 'Select B.name FROM BUILDING AS B;';
                        $stmt = $PDO->prepare($Query);
                        $stmt->execute();
                        while ($row = $stmt->fetch()) {
                            echo '<option value = ' . $row->name . '>' . $row->name . '</option>';
                        }
                        ?>
                    </select>
                </label>
                <br>
                <label for="Parent"> Parent_ID:
                    <input type="text" , name="Parent_ID">
                </label>
                <br>
                <input type='submit' value="Add Event">

            </form>
            <?php
            if (isset($_POST['Name'])   &&
                isset($_POST['Time'])   &&
                isset($_POST['Cost'])   &&
                isset($_POST['Building'])   &&
                isset($_POST['Parent_ID']))
                {
                    $Query = 'INSERT INTO EVENT VALUES' .
                    '(:name, :time, :cost, :building, :parent_ID);';
                    $stmt = $PDO -> prepare(['name' => $_POST['Name'],
                    'Time' => $_POST['Time'], 'Cost' => $_POST['Cost'],
                    'Building' => $_POST['Building'],'parent_ID' => $_POST['Parent_ID']] );
                    $stmt ->execute();
                }
            ?>

        </div>
        <br>
        <div>
            <?php

            $Query = 'CALL Get_EVENTS( :dep_id )';
            $stmt = $PDO->prepare($Query);
            $stmt->execute(['dep_id' => $_SESSION['User']->d_no]);
            $check = $stmt->fetch();
            while ($row = $stmt->fetch()) {
                echo 'Event Name: ' . htmlspecialchars($row->name) . '<br>';
                echo 'Event time: ' . htmlspecialchars($row->TIME) . '<br>';
                echo 'Event cost: ' . htmlspecialchars($row->COST) . '<br>';
                echo 'Event capacity: ' . htmlspecialchars($row->CAPACITY) . '<br>';
                echo 'Event location: ' . htmlspecialchars($row->B_NAME) . '<br>';
                echo 'Event Department: ' . htmlspecialchars($row->DEP_ID) . '<br>';
                echo
                '<form action = \'Manager_Events.phtml\' method = \'post\'>
                <input type="hidden" name="delete" value="yes">
                <input type="submit" value="Delete Event"></form>';

            }


            ?>
            <form action="Manger_Events.phtml" method='post'>


            </form>
        </div>
    </div>


</body>

